easy_recipe/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('ingredients/', include('ingredients.urls')),
    path('recipes/', include('recipes.urls'))
]

home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path("", views.index, name="index")
]

ingredients/urls.py
from django.urls import path

from . import views

app_name = "ingredients"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("add/", views.AddIngredientView.as_view(), name="add_ingredient"),
    path("<int:pk>/", views.IngredientDetailsView.as_view(), name="details"),
    path("<int:pk>/edit/", views.EditIngredientView.as_view(), name="edit_ingredient")
]

recipes/urls.py
from django.urls import path

from . import views

app_name = "recipes"

urlpatterns = [
    path("", views.SeeAllRecipesView.as_view(), name="index"),
    path("add/", views.AddRecipeView.as_view(), name="add_recipe"),
    path("<int:pk>/", views.RecipeDetailsView.as_view(), name="details"),
    path("<int:pk>/edit/", views.EditRecipeView.as_view(), name="edit_recipe")
]

home/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'home/index.html')

home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Easy Recipe - Home</title>
    <link rel="stylesheet" href="{% static "home/styles.css" %}">
</head>
<body>
    <header>
        <div class="container">
            <h1>Easy Recipe</h1>
            <h2>Effortless recipe management at your fingertips.</h2>
        </div>
    </header>
    <main>
        <section id="action-section">
            <h1>What would you like to do?</h1>
            <div class="app-links">
                <a href="{% url 'ingredients:index' %}" class="button">Manage Ingredients</a>
                <a href="{% url 'recipes:index' %}" class="button">Manage Recipes</a>
            </div>
        </section>
    </main>
</body>
</html>