easy_recipe/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('ingredients/', include('ingredients.urls')),
    path('recipes/', include('recipes.urls'))
]

home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path("", views.index, name="index")
]

ingredients/urls.py
from django.urls import path

from . import views

app_name = "ingredients"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("add/", views.AddIngredientView.as_view(), name="add_ingredient"),
    path("<int:pk>/", views.IngredientDetailsView.as_view(), name="details"),
    path("<int:pk>/edit/", views.EditIngredientView.as_view(), name="edit_ingredient")
]

ingredients/models.py
from django.db import models
from django.core.validators import MinLengthValidator, MaxLengthValidator, MinValueValidator
from djmoney.models.fields import MoneyField

from enum import Enum

class Unit(Enum):
    GRAM = 'g'
    KILOGRAM = 'Kg'
    LITER = 'L'
    CENTILITER = 'cl'

class Ingredient(models.Model):
    name = models.CharField(max_length=100)
    ean = models.CharField(primary_key=True, max_length=13, validators=[MinLengthValidator(13), MaxLengthValidator(13)])
    standard_amount = models.BigIntegerField(validators=[MinValueValidator(0)])
    standard_unit = models.CharField(max_length=20, choices=[(unit.name, unit.value) for unit in Unit])
    cost_per_unit = MoneyField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name

ingredients/forms.py
from django import forms
from djmoney.forms.fields import MoneyField
from currency_converter.currency_converter import CurrencyConverter
from babel.numbers import get_currency_name

from .models import Ingredient

class AddIngredientForm(forms.ModelForm):
    suported_currencies = CurrencyConverter().currencies
    cost_per_unit = MoneyField(
        currency_choices=[(currency, get_currency_name(currency, locale="en_US")) for currency in suported_currencies],
        max_digits=10,
        decimal_places=2,
        default_currency='EUR',
        default_amount=1
    )

    class Meta:
        model = Ingredient
        fields = "__all__"

ingredients/views.py
from django.urls import reverse_lazy
from django.views import generic
from django.db.models import Q as FilterParam

from .forms import AddIngredientForm
from .models import Ingredient

class IndexView(generic.ListView):
    template_name = "ingredients/index.html"
    context_object_name = "ingredient_list"
    
    def get_queryset(self):
        search = self.request.GET.get('search_param', '')

        if search:
            return Ingredient.objects.filter(FilterParam(name__icontains=search) | FilterParam(ean__icontains=search))
        
        return Ingredient.objects.all()
    
class IngredientDetailsView(generic.DetailView):
    template_name = "ingredients/ingredient_details.html"
    model = Ingredient

class AddIngredientView(generic.CreateView):
    model = Ingredient
    form_class = AddIngredientForm
    template_name = "ingredients/add_ingredient.html"
    success_url = reverse_lazy('ingredients:index')

class EditIngredientView(generic.UpdateView):
    model = Ingredient
    form_class = AddIngredientForm
    template_name = "ingredients/edit_ingredient.html"
    success_url = reverse_lazy('ingredients:index')

ingredients/templates/ingredients/add_ingredient.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'ingredients/styles.css' %}">
        <link rel="stylesheet" href="{% static 'ingredients/add-ingredient.css' %}">
        <title>Add new ingredient</title>
    </head>
    <body>
        <header>
            <div class="container">
                <h1>Add a new ingredient to your inventory</h1>
            </div>
        </header>
        <main class="container">
            <form action="{% url "ingredients:add_ingredient" %}" method="POST">
                {% csrf_token %}
                {{ form }}

                <div class="action-buttons">
                    <input type="submit" class="button" value="Save">
                    <a class="cancel-button" href="{% url "ingredients:index" %}">Cancel</a>
                </div>
            </form>
        </main>
    </body>
</html>

ingredients/templates/ingredients/edit_ingredient.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'ingredients/styles.css' %}">
        <link rel="stylesheet" href="{% static 'ingredients/add-ingredient.css' %}">
        <title>Edit new ingredient</title>
    </head>
    <body>
        <header>
            <h1>Edit ingredient</h1>
        </header>
        <main>
            <form action="{% url "ingredients:edit_ingredient" ingredient.ean %}" method="POST">
                {% csrf_token %}
                {{ form }}
                <div class="action-buttons">
                    <input class="button" type="submit" value="Save changes">
                    <a class="button cancel-button" href="{% url "ingredients:index" %}">Cancel</a>
                </div>
            </form>
        </main>
    </body>
</html>

ingredients/templates/ingredients/index.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ingredients</title>
    <link rel="stylesheet" href="{% static 'ingredients/styles.css' %}">
    <link rel="stylesheet" href="{% static 'ingredients/index.css' %}">
</head>
<body>
    <header>
        <div class="container">
            <h1>Managing ingredients has just become easy and fun!</h1>
        </div>
    </header>
    <main>
        <form method="GET" action="" id="search-form">
            <input type="text" name="search_param" placeholder="Search by name or EAN" value="{{ request.GET.search_param }}">
            <button class="button" type="submit">Search</button>
        </form>

        {% if ingredient_list %}
            <ul id="ingredient-list">
                {% for ingredient in ingredient_list %}
                    <li class="ingredient-item">
                        <div class="ingredient-item">
                            <h3 class="name">{{ingredient.name}}</h3>
                            <span class="price">Cost per unit({{ingredient.standard_unit}}): {{ingredient.cost_per_unit}}</span>
                            <a href="{% url 'ingredients:details' ingredient.ean %}"> See details </a>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <span id="no-ingredients-message"> No ingredients found.</span>
        {% endif %}
        
        <nav>
            <a href="{% url 'ingredients:add_ingredient' %}" class="button"> Add Ingredient</a>
            <a href="{% url 'home:index' %}" class="button cancel-button">Home</a>
        </nav>  
    </main>
</body>
</html>

ingredients/templates/ingredients/ingredient_details.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'ingredients/styles.css' %}">
        <link rel="stylesheet" href="{% static 'ingredients/details.css' %}">
        <title>Easy Recipe - Ingredient Details</title>
    </head>
    <body>
        <header>
            <div class="container">
                <h1>Ingredient Details</h1>
            </div>
        </header>
        <main class="container">
            <section class="ingredient-details">
                <h1>Name: {{ingredient.name}}</h1>
                <h2>EAN: {{ingredient.ean}}</h2>
                <p>Price: {{ingredient.cost_per_unit}} ({{ingredient.standard_amount}} {{ingredient.standard_unit}}{{ingredient.standard_amount|pluralize}})</p>
            </section>

            <div class="buttons-container">
                <a class="button" href="{% url "ingredients:edit_ingredient" ingredient.ean %}">Edit ingredient</a>
                <a class="cancel-button" href="{% url "ingredients:index" %}">Go back</a>
            </div>
        </main>
    </body>
</html>