easy_recipe/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('ingredients/', include('ingredients.urls')),
    path('recipes/', include('recipes.urls'))
]

home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path("", views.index, name="index")
]

recipes/urls.py
from django.urls import path

from . import views

app_name = "recipes"

urlpatterns = [
    path("", views.SeeAllRecipesView.as_view(), name="index"),
    path("add/", views.AddRecipeView.as_view(), name="add_recipe"),
    path("<int:pk>/", views.RecipeDetailsView.as_view(), name="details"),
    path("<int:pk>/edit/", views.EditRecipeView.as_view(), name="edit_recipe")
]

recipes/models.py
from functools import reduce
from django.core.validators import MinValueValidator, MinLengthValidator
from django.db import models
from djmoney.money import Money

from ingredients.models import Ingredient

from .helpers import EurConverter

class Recipe(models.Model):
    name = models.CharField(max_length=100, validators=[MinLengthValidator(3)])
    ingredients = models.ManyToManyField(Ingredient, through='RecipeIngredient')

    def get_total_cost_in_eur(self):
        recipe_ingredients = RecipeIngredient.objects.filter(recipe=self)
        individual_ingredients_cost = map(lambda ingredient: ingredient.get_cost_in_eur(), recipe_ingredients)
        total_cost = reduce(lambda cost_one, cost_two: cost_one + cost_two, individual_ingredients_cost, Money(0, 'EUR'))
        return total_cost


class RecipeIngredient(models.Model):
    ingredient = models.ForeignKey(Ingredient, on_delete=models.RESTRICT)
    amount = models.FloatField(validators=[MinValueValidator(0)])
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)

    def get_cost_in_eur(self):
        cost_in_registered_currency = self.amount * (self.ingredient.cost_per_unit / self.ingredient.standard_amount)
        eur_converter = EurConverter()
        return eur_converter.convert(cost_in_registered_currency)

ingredients/views.py
from django.urls import reverse_lazy
from django.views import generic
from django.db.models import Q as FilterParam

from .forms import AddIngredientForm
from .models import Ingredient

class IndexView(generic.ListView):
    template_name = "ingredients/index.html"
    context_object_name = "ingredient_list"
    
    def get_queryset(self):
        search = self.request.GET.get('search_param', '')

        if search:
            return Ingredient.objects.filter(FilterParam(name__icontains=search) | FilterParam(ean__icontains=search))
        
        return Ingredient.objects.all()
    
class IngredientDetailsView(generic.DetailView):
    template_name = "ingredients/ingredient_details.html"
    model = Ingredient

class AddIngredientView(generic.CreateView):
    model = Ingredient
    form_class = AddIngredientForm
    template_name = "ingredients/add_ingredient.html"
    success_url = reverse_lazy('ingredients:index')

class EditIngredientView(generic.UpdateView):
    model = Ingredient
    form_class = AddIngredientForm
    template_name = "ingredients/edit_ingredient.html"
    success_url = reverse_lazy('ingredients:index')

recipes/views.py
from django.db import transaction
from django.forms import ValidationError
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views import generic

from ingredients.models import Ingredient

from .models import Recipe, RecipeIngredient

class SeeAllRecipesView(generic.ListView):
    context_object_name = 'recipe_list'
    template_name = 'recipes/index.html'

    def get_queryset(self):
        return Recipe.objects.all()

class RecipeDetailsView(generic.DetailView):
    template_name = 'recipes/recipe_details.html'
    model = Recipe

class AddRecipeView(generic.TemplateView):
    template_name = 'recipes/add_recipe.html'

    def post(self, request, *args, **kwargs):
        recipe_name = request.POST.get('name', '')
        recipe_ingredients = self.extract_recipe_ingredients()
        try:
            self.store_recipe(recipe_name, recipe_ingredients)
            return HttpResponseRedirect(reverse('recipes:index'))
        except ValidationError as e:
            errors = e.message_dict
            return self.render_to_response(self.get_context_data(errors = errors, name=recipe_name, ingredients=recipe_ingredients))
        
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["ingredient_list"] = list(Ingredient.objects.all().values('ean', 'name', 'standard_unit'))
        return context
    
    def extract_recipe_ingredients(self):
        request_data = self.request.POST
        ingredients = []
        recipe_ingrediet_keys = filter(lambda key: key.startswith('ingredients[') and key.endswith('[ean]'), request_data.keys())

        for recipe_ingredient in recipe_ingrediet_keys:
            key = recipe_ingredient[0:14]
            ingredient = {
                'ean': request_data.get(f'{key}[ean]'),
                'amount': request_data.get(f'{key}[amount]')
            }
            ingredients.append(ingredient)
        
        return ingredients
    
    
    @transaction.atomic
    def store_recipe(self, name, recipe_ingredients):
        recipe = Recipe.objects.create(name = name)
        recipe.full_clean()
        self.store_ingredients(recipe=recipe, recipe_ingredients=recipe_ingredients)

    def store_ingredients(self, recipe, recipe_ingredients):
        print('Running base store ingredients')
        if (not recipe_ingredients):
            raise ValidationError({'ingredients': 'A recipe must have at least 1 ingredient.'})
        
        for recipe_ingredient_data in recipe_ingredients:
            ingredient = get_object_or_404(Ingredient, pk=recipe_ingredient_data['ean'])
            amount = recipe_ingredient_data['amount']

            if (not amount or float(amount) <= 0):
                raise ValidationError({'ingredients': 'All ingredients must have a non-zero amount'})

            RecipeIngredient.objects.create(ingredient=ingredient, amount=amount, recipe=recipe)

class EditRecipeView(AddRecipeView):
    template_name = 'recipes/edit_recipe.html'

    def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            recipe = get_object_or_404(Recipe, pk=self.kwargs.get('pk'))
            context["name"] = recipe.name
            context["recipe"] = recipe
            context["ingredients"] = self.get_recipe_ingredients_for_context(recipe)
            return context

    def get_recipe_ingredients_for_context(self, recipe):
        context_recipe_ingredients = []
        
        for recipe_ingredient in recipe.recipeingredient_set.all():
            context_recipe_ingredients.append({
                "ean": recipe_ingredient.ingredient.ean,
                "amount": recipe_ingredient.amount
            })
        
        return context_recipe_ingredients
    
    @transaction.atomic
    def store_recipe(self, name, recipe_ingredients):
        recipe_id = self.kwargs.get('pk')
        recipe = get_object_or_404(Recipe, pk=recipe_id)
        recipe.name = name
        recipe.full_clean()
        recipe.save()

        self.store_ingredients(recipe=recipe, recipe_ingredients=recipe_ingredients)

    def store_ingredients(self, recipe, recipe_ingredients):
        if (not recipe_ingredients):
            raise ValidationError({'ingredients': 'A recipe must have at least 1 ingredient.'})

        current_recipe_ingredients_eans = list(map(lambda ingredient: ingredient.ean, recipe.ingredients.all()))
        recipe_ingredients_eans_from_request = list(map(lambda recipe_ingredient: recipe_ingredient['ean'], recipe_ingredients))
        removed_ingredients = list(filter(lambda ean: ean not in recipe_ingredients_eans_from_request, current_recipe_ingredients_eans))
        added_ingredients = list(filter(lambda ingredient: ingredient['ean'] not in current_recipe_ingredients_eans, recipe_ingredients))
        modified_ingredients = list(filter(lambda ingredient: ingredient['ean'] in current_recipe_ingredients_eans, recipe_ingredients))

        
        RecipeIngredient.objects.filter(recipe_id=recipe.id, ingredient_id__in=removed_ingredients).delete()
        
        for added_ingredient in added_ingredients:
            amount = added_ingredient['amount']
            if (not amount or float(amount) <= 0):
                raise ValidationError({'ingredients': 'All ingredients must have a non-zero amount'})

            ingredient = get_object_or_404(Ingredient, pk=added_ingredient['ean'])
            RecipeIngredient.objects.create(ingredient=ingredient, amount=amount, recipe=recipe)
        
        for modified_ingredient in modified_ingredients:
            amount = modified_ingredient['amount']
            if (not amount or float(amount) <= 0):
                raise ValidationError({'ingredients': 'All ingredients must have a non-zero amount'})
            recipe_ingredient = get_object_or_404(RecipeIngredient, recipe_id=recipe.id, ingredient_id=modified_ingredient['ean'])
            recipe_ingredient.amount = amount
            recipe_ingredient.save()
        

recipes/templates/recipes/add_recipe.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'recipes/styles.css' %}">
        <link rel="stylesheet" href="{% static 'recipes/add-recipe.css' %}">
        <title>Easy Recipe - Add new recipe</title>
    </head>
    <body>
        <header>
            <div class="container">
                <h1>Add a new recipe</h1>
            </div>
        </header>
        <main>
            <form action="{% url "recipes:add_recipe" %}" method="POST">
                {% csrf_token %}
             
                <div class="recipe-name-input-container">
                    <label for="name">Recipe name</label>
                    <input type="text" name="name" id="name" value={{ name|default:""|safe }}>
                    {% if errors.name %}
                    <span class="error">{{errors.name.0}}</span>
                    {% endif %}
                </div>

                <section class="ingredients">
                    {% if errors.ingredients %}
                        <span class="error">{{errors.ingredients.0}}</span>
                    {% endif %}

                    {% if ingredients %}
                        {% for ingredient in ingredients %}
                            <fieldset class="recipe-ingredient">
                                <label for="ingredient">Ingredient</label>
                                <select name="ingredients[{{forloop.counter0}}][ean]">
                                    {% for ingredient_from_db in ingredient_list %}
                                        <option value="{{ingredient_from_db.ean}}" {% if ingredient_from_db.ean == ingredient.ean %} selected {% endif %}>
                                            {{ingredient_from_db.name}} ({{ingredient_from_db.standard_unit}})
                                        </option>
                                    {% endfor %}
                                </select>
                                <label for="amount">Amount</label>
                                <input type="number" name="ingredients[{{forloop.counter0}}][amount]" id="amount" min="0" step="0.1" value="{{ingredient.amount}}">
                                <button type="button" class="remove-ingredient-btn cancel-button">Remove</button>
                            </fieldset>    
                        {% endfor %}
                    {% endif %}
                </section>
                
                <button class="button add-ingredient-button" type="button" onclick="createRecipeIngredient()">Add ingredient</button>
                
                <div class="action-buttons">
                    <input class="button" type="submit" value="Save Recipe">
                    <a class="cancel-button" href="{% url "recipes:index" %}">Cancel</a>
                </div>
                
            </form>
        </main>
        {{ingredient_list|json_script:"ingredient_list"}}
        <script src="{% static "recipes/add_ingredient.js" %}"></script>
    </body>
</html>

recipes/templates/recipes/edit_recipe.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'recipes/styles.css' %}">
        <link rel="stylesheet" href="{% static 'recipes/add-recipe.css' %}">
        <title>Easy Recipe - Edit Recipe</title>
    </head>
    <body>
        <header>
            <div class="container">
                <h1>Edit a recipe</h1>
            </div>
        </header>
        <main>
            <form action="{% url "recipes:edit_recipe" recipe.id %}" method="POST">
                {% csrf_token %}
                <div class="recipe-name-input-container">
                    <label for="name">Recipe name</label>
                    <input type="text" name="name" id="name" value="{{ name|default:"" }}">
                    {% if errors.name %}
                        <span class="error">{{errors.name.0}}</span>
                    {% endif %}
                </div>
                
                <section class="ingredients">
                    <h2>Ingredients</h2>
                    {% if errors.ingredients %}
                        <span class="error">{{errors.ingredients.0}}</span>
                    {% endif %}

                    {% if ingredients %}
                        {% for ingredient in ingredients %}
                            <fieldset class="recipe-ingredient">
                                <label for="ingredient">Ingredient</label>
                                <select name="ingredients[{{forloop.counter0}}][ean]">
                                    {% for ingredient_from_db in ingredient_list %}
                                        <option value="{{ingredient_from_db.ean}}" {% if ingredient_from_db.ean == ingredient.ean %} selected {% endif %}>
                                            {{ingredient_from_db.name}} ({{ingredient_from_db.standard_unit}})
                                        </option>
                                    {% endfor %}
                                </select>
                                <label for="amount">Amount</label>
                                <input type="number" name="ingredients[{{forloop.counter0}}][amount]" id="amount" min="0" step="0.1" value="{{ingredient.amount}}">
                                <button type="button" class="remove-ingredient-btn cancel-button">Remove</button>
                            </fieldset>    
                        {% endfor %}
                    {% endif %}
                </section>
                
                <button class="button add-ingredient-button" type="button" onclick="createRecipeIngredient()">Add ingredient</button>

                <div class="action-buttons">
                    <input class="button" type="submit" value="Save Recipe">
                    <a class="cancel-button" href="{% url "recipes:details" recipe.id%}">Cancel</a>
                </div>
            </form>
        </main>
        {{ingredient_list|json_script:"ingredient_list"}}
        <script src="{% static "recipes/add_ingredient.js" %}"></script>
    </body>
</html>

recipes/templates/recipes/index.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'recipes/styles.css' %}">
        <link rel="stylesheet" href="{% static 'recipes/index.css' %}">
        <title>Recipes</title>
    </head>
    <body>
        <header>
            <h1>Managing recipes is simple and easy...</h1>
        </header>
        <main>
            {% if recipe_list %}
            <ul class="recipe-list">
                {% for recipe in  recipe_list %}
                <li class="recipe-details">
                    <div class="recipe-details">
                        <h2>{{ recipe.name }}</h2>
                        <p>Number of ingredients: {{recipe.ingredients.count}}</p>
                        <strong>Total cost: {{recipe.get_total_cost_in_eur}}</strong>
                        <a href="{% url "recipes:details" recipe.id%}">See details</a>
                    </div>
                </li>
                {% endfor %}
            </ul>
            {% else %}
                <p class="no-recipes-message">No recipes found.</p>
            {% endif %}
            
            <nav>
                <a class="button" href="{% url "recipes:add_recipe" %}">Add new recipe</a>
                <a class="button cancel-button" href="{% url "home:index" %}">Home</a>
            </nav>
        </main>
    </body>
</html>

recipes/templates/recipes/recipe_details.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'recipes/styles.css' %}">
        <link rel="stylesheet" href="{% static 'recipes/details.css' %}">
        <title>Easy Recipe - Recipe Details</title>
    </head>
    <body>
        <header>
            <div class="container">
                <h1>Recipe Details</h1>
            </div>
        </header>
        <main class="container">
            <section class="recipe-details">
                <h1 class="recipe-name">{{recipe.name}}</h1>
                <h2 class="recipe-cost">Total Cost: {{recipe.get_total_cost_in_eur}}</h2>
            </section>

            <section class="ingredient-details">
                <table class="ingredients">
                    <caption>Ingredients</caption>
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Amount</th>
                            <th>Cost</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for recipe_ingredient in recipe.recipeingredient_set.all %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td>{{recipe_ingredient.ingredient.name}}</td>
                                <td>{{recipe_ingredient.amount}} {{recipe_ingredient.ingredient.standard_unit}}</td>
                                <td>{{recipe_ingredient.get_cost_in_eur}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </section>
            
            <nav>
                <a class="button" href="{% url "recipes:edit_recipe" recipe.id%}">Edit Recipe</a>
                <a class="cancel-button" href="{% url "recipes:index" %}">Go back</a>
            </nav>
        </main>
    </body>
</html>